#!/bin/zsh
# command -v docker > /dev/null 2>&1 && {
#   function ncmpcpp() {
#     docker run --rm --name ncmpcpp --network mopidy_default -it imdevinc/ncmpcpp ncmpcpp mopidy --host mopidy
#   }
# }
