#!/bin/zsh
if [[ -d "$HOME/.go" ]]; then
    export GOPATH="$HOME/.go"
fi

if [[ -d "${GOPATH}/bin" ]]; then
    export PATH="${PATH}:${GOPATH}/bin"
fi

if [[ -d "/usr/local/go/bin" ]]; then
    export PATH="${PATH}:/usr/local/go/bin"
fi