#!/bin/zsh
if [[ -f "/usr/bin/virtualenvwrapper.sh" ]]; then
  export WORKON_HOME=$HOME/.virtualenvs
  export PROJECT_HOME=$HOME/Projects
  if [[ ! -d $WORKON_HOME ]]; then
    mkdir $WORKON_HOME
  fi
  source /usr/bin/virtualenvwrapper.sh
fi

if [[ -f "/usr/local/bin/virtualenvwrapper.sh" ]]; then
  export VIRTUALENVWRAPPER_PYTHON=`which python3`
  export WORKON_HOME=$HOME/.virtualenvs
  export PROJECT_HOME=$HOME/Projects
  if [[ ! -d $WORKON_HOME ]]; then
    mkdir $WORKON_HOME
  fi
  source /usr/local/bin/virtualenvwrapper.sh
fi